@echo off
echo Starting CodeInsight Backend...
start "Backend" cmd /k "cd /d "%~dp0backend" && npm install && npm run dev"
echo Waiting 8 seconds for backend...
timeout /t 8 /nobreak >nul
echo Starting CodeInsight Frontend...
start "Frontend" cmd /k "cd /d "%~dp0frontend" && npm install && npm run dev"
echo Done. Backend: http://localhost:5000 | Frontend: http://localhost:5173
